### PR TITLE
Handle asynchronous uncaught errors with domains

### LINKED ISSUE #155: nodeunit should catch exceptions and report them as failures
right now if a test throws an exception, the process just exits.

### PR DESCRIPTION
**Pull request by rpaterson**
Fixes #155, #177, #279

[Review on Reviewable](https://reviewable.io/reviews/caolan/nodeunit/281)

### CODE REVIEW

**Comment by mattheworiordan** [comment]
I am using this fork, it's great, thanks @rpaterson.  I am amazed that this is not merged into `master` given how invaluable it is. :+1:

**Comment by rpaterson** [comment]
Fixed a bug with the original patch when test throws both sync and async errors.

**Comment by mreinstein** [comment]
it's a clever solution but given that domains are deprecated in node, closing this. see:

https://nodejs.org/dist/latest-v6.x/docs/api/domain.html

**Comment by rpaterson** [comment]
@mreinstein the doc you linked says:
```
This module is pending deprecation. Once a replacement API has been finalized, this module will be fully deprecated. Most end users should not have cause to use this module. Users who absolutely must have the functionality that domains provide may rely on it for the time being but should expect to have to migrate to a different solution in the future.
```

I'm all for a better solution when one becomes available, but right now domains seem to be the only practical way to solve this.

**Comment by mreinstein** [comment]
I hear ya. I just can't justify putting something into nodeunit which has stability level 0. I know it solves several issues but it just doesn't make sense to bank on an API that is definitely going away.

**Pull request closed without merging**
